# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.17)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget ShishGL ShishGL-Core ShishGL-LogSystem ShishGL-EventSystem ShishGL-ResourceManager ShishGL-Primitives ShishGL-RenderSystem ShishGL-GraphicsPlatform ShishGL-PlatformInput ShishGL-PlatformEvents ShishGL-SfmlPlatform ShishGL-Window ShishGL-GUI ShishGL-UIWindow ShishGL-Behaviors ShishGL-Styles ShishGL-Shapes ShishGL-DebugUtilities)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target ShishGL
add_library(ShishGL INTERFACE IMPORTED)

set_target_properties(ShishGL PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL"
  INTERFACE_LINK_LIBRARIES "ShishGL-Core;ShishGL-DebugUtilities;ShishGL-GUI"
)

# Create imported target ShishGL-Core
add_library(ShishGL-Core STATIC IMPORTED)

set_target_properties(ShishGL-Core PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core"
  INTERFACE_LINK_LIBRARIES "ShishGL-Primitives;ShishGL-LogSystem;ShishGL-ResourceManager;ShishGL-EventSystem;ShishGL-RenderSystem;ShishGL-Window"
  INTERFACE_SOURCES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/CoreApplication.hpp"
)

# Create imported target ShishGL-LogSystem
add_library(ShishGL-LogSystem STATIC IMPORTED)

set_target_properties(ShishGL-LogSystem PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/LogSystem"
  INTERFACE_LINK_LIBRARIES "ShishGL-Primitives"
  INTERFACE_SOURCES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/LogSystem/LogSystem.hpp"
)

# Create imported target ShishGL-EventSystem
add_library(ShishGL-EventSystem STATIC IMPORTED)

set_target_properties(ShishGL-EventSystem PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/EventSystem"
  INTERFACE_LINK_LIBRARIES "ShishGL-LogSystem;ShishGL-Primitives"
  INTERFACE_SOURCES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/EventSystem/Event.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/EventSystem/EventManager.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/EventSystem/Listener.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/EventSystem/SubscriptionManager.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/EventSystem/EventSystem.hpp"
)

# Create imported target ShishGL-ResourceManager
add_library(ShishGL-ResourceManager STATIC IMPORTED)

set_target_properties(ShishGL-ResourceManager PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/ResourceManager/"
  INTERFACE_SOURCES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/ResourceManager//ResourceManager.hpp"
)

# Create imported target ShishGL-Primitives
add_library(ShishGL-Primitives STATIC IMPORTED)

set_target_properties(ShishGL-Primitives PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/Primitives"
  INTERFACE_SOURCES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/Primitives/Frame.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/Primitives/Vector2.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/Primitives/Segment2.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/Primitives/Color.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/Primitives/Time.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/Primitives/Vector3.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/Primitives/Text.hpp"
)

# Create imported target ShishGL-RenderSystem
add_library(ShishGL-RenderSystem STATIC IMPORTED)

set_target_properties(ShishGL-RenderSystem PROPERTIES
  INTERFACE_COMPILE_OPTIONS "-march=native"
  INTERFACE_INCLUDE_DIRECTORIES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/RenderSystem"
  INTERFACE_LINK_LIBRARIES "ShishGL-LogSystem;ShishGL-GraphicsPlatform;ShishGL-SfmlPlatform"
  INTERFACE_SOURCES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/RenderSystem/RenderSystem.hpp"
)

# Create imported target ShishGL-GraphicsPlatform
add_library(ShishGL-GraphicsPlatform STATIC IMPORTED)

set_target_properties(ShishGL-GraphicsPlatform PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/RenderSystem/GraphicsPlatform"
  INTERFACE_LINK_LIBRARIES "ShishGL-Primitives;ShishGL-LogSystem;ShishGL-ResourceManager;ShishGL-PlatformEvents;ShishGL-PlatformInput"
  INTERFACE_SOURCES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/RenderSystem/GraphicsPlatform/IPlatform.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/RenderSystem/GraphicsPlatform/Image.hpp"
)

# Create imported target ShishGL-PlatformInput
add_library(ShishGL-PlatformInput STATIC IMPORTED)

set_target_properties(ShishGL-PlatformInput PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/RenderSystem/GraphicsPlatform/Input"
  INTERFACE_SOURCES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/RenderSystem/GraphicsPlatform/Input/Mouse.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/RenderSystem/GraphicsPlatform/Input/Keyboard.hpp"
)

# Create imported target ShishGL-PlatformEvents
add_library(ShishGL-PlatformEvents STATIC IMPORTED)

set_target_properties(ShishGL-PlatformEvents PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/RenderSystem/GraphicsPlatform/Events"
  INTERFACE_LINK_LIBRARIES "ShishGL-EventSystem;ShishGL-PlatformInput"
  INTERFACE_SOURCES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/RenderSystem/GraphicsPlatform/Events/PlatformListener.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/RenderSystem/GraphicsPlatform/Events/KeyboardEvent.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/RenderSystem/GraphicsPlatform/Events/MouseEvent.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/RenderSystem/GraphicsPlatform/Events/TimerEvent.hpp"
)

# Create imported target ShishGL-SfmlPlatform
add_library(ShishGL-SfmlPlatform STATIC IMPORTED)

set_target_properties(ShishGL-SfmlPlatform PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/RenderSystem/SfmlPlatform"
  INTERFACE_LINK_LIBRARIES "ShishGL-GraphicsPlatform;sfml-system;sfml-window;sfml-graphics"
  INTERFACE_SOURCES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/RenderSystem/SfmlPlatform/Platform.hpp"
)

# Create imported target ShishGL-Window
add_library(ShishGL-Window STATIC IMPORTED)

set_target_properties(ShishGL-Window PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/Window"
  INTERFACE_LINK_LIBRARIES "ShishGL-LogSystem;ShishGL-RenderSystem"
  INTERFACE_SOURCES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/Window/Window.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/Core/Window/WindowManager.hpp"
)

# Create imported target ShishGL-GUI
add_library(ShishGL-GUI STATIC IMPORTED)

set_target_properties(ShishGL-GUI PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI"
  INTERFACE_LINK_LIBRARIES "ShishGL-Core;ShishGL-UIWindow;ShishGL-Styles;ShishGL-Shapes;ShishGL-Behaviors"
  INTERFACE_SOURCES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/GUI.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIDialog.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UICanvas.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIButton.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UISwitch.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UISlider.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIScrollbar.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIFrame.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UISelectList.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UITextInput.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIFileSelector.hpp"
)

# Create imported target ShishGL-UIWindow
add_library(ShishGL-UIWindow STATIC IMPORTED)

set_target_properties(ShishGL-UIWindow PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIWindow"
  INTERFACE_LINK_LIBRARIES "ShishGL-Window;ShishGL-Shapes"
  INTERFACE_SOURCES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIWindow/Style.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIWindow/Behavior.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIWindow/UIWindow.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIWindow/UIWindow.ipp"
)

# Create imported target ShishGL-Behaviors
add_library(ShishGL-Behaviors STATIC IMPORTED)

set_target_properties(ShishGL-Behaviors PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIWindow/Behaviors"
  INTERFACE_LINK_LIBRARIES "ShishGL-Core;ShishGL-UIWindow"
  INTERFACE_SOURCES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIWindow/Behaviors/Behaviors.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIWindow/Behaviors/DefaultBehavior.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIWindow/Behaviors/Clickable.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIWindow/Behaviors/Draggable.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIWindow/Behaviors/Slidable.hpp"
)

# Create imported target ShishGL-Styles
add_library(ShishGL-Styles INTERFACE IMPORTED)

set_target_properties(ShishGL-Styles PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIWindow/Styles"
  INTERFACE_LINK_LIBRARIES "ShishGL-Core;ShishGL-Shapes"
  INTERFACE_SOURCES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIWindow/Styles/Styles.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIWindow/Styles/ColorFill.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIWindow/Styles/TextureFill.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIWindow/Styles/Bordered.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIWindow/Styles/Font.hpp"
)

# Create imported target ShishGL-Shapes
add_library(ShishGL-Shapes STATIC IMPORTED)

set_target_properties(ShishGL-Shapes PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIWindow/Shapes"
  INTERFACE_LINK_LIBRARIES "ShishGL-Core"
  INTERFACE_SOURCES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIWindow/Shapes/Shapes.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIWindow/Shapes/Shape2D.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIWindow/Shapes/RectangleShape.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/GUI/UIWindow/Shapes/CircleShape.hpp"
)

# Create imported target ShishGL-DebugUtilities
add_library(ShishGL-DebugUtilities STATIC IMPORTED)

set_target_properties(ShishGL-DebugUtilities PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/DebugUtilities"
  INTERFACE_LINK_LIBRARIES "ShishGL-GUI"
  INTERFACE_SOURCES "/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/DebugUtilities/FpsLabel.hpp;/home/shishqa/MIPT/2020_3/00_ShishGL/include/ShishGL/DebugUtilities/GradeCanvas.hpp"
)

# Import target "ShishGL-Core" for configuration "Release"
set_property(TARGET ShishGL-Core APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ShishGL-Core PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/shishqa/MIPT/2020_3/02_YAGE/Release/ShishGL/src/Core/libShishGL-Core.a"
  )

# Import target "ShishGL-LogSystem" for configuration "Release"
set_property(TARGET ShishGL-LogSystem APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ShishGL-LogSystem PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/shishqa/MIPT/2020_3/02_YAGE/Release/ShishGL/src/Core/LogSystem/libShishGL-LogSystem.a"
  )

# Import target "ShishGL-EventSystem" for configuration "Release"
set_property(TARGET ShishGL-EventSystem APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ShishGL-EventSystem PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/shishqa/MIPT/2020_3/02_YAGE/Release/ShishGL/src/Core/EventSystem/libShishGL-EventSystem.a"
  )

# Import target "ShishGL-ResourceManager" for configuration "Release"
set_property(TARGET ShishGL-ResourceManager APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ShishGL-ResourceManager PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/shishqa/MIPT/2020_3/02_YAGE/Release/ShishGL/src/Core/ResourceManager/libShishGL-ResourceManager.a"
  )

# Import target "ShishGL-Primitives" for configuration "Release"
set_property(TARGET ShishGL-Primitives APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ShishGL-Primitives PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/shishqa/MIPT/2020_3/02_YAGE/Release/ShishGL/src/Core/Primitives/libShishGL-Primitives.a"
  )

# Import target "ShishGL-RenderSystem" for configuration "Release"
set_property(TARGET ShishGL-RenderSystem APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ShishGL-RenderSystem PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/shishqa/MIPT/2020_3/02_YAGE/Release/ShishGL/src/Core/RenderSystem/libShishGL-RenderSystem.a"
  )

# Import target "ShishGL-GraphicsPlatform" for configuration "Release"
set_property(TARGET ShishGL-GraphicsPlatform APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ShishGL-GraphicsPlatform PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/shishqa/MIPT/2020_3/02_YAGE/Release/ShishGL/src/Core/RenderSystem/GraphicsPlatform/libShishGL-GraphicsPlatform.a"
  )

# Import target "ShishGL-PlatformInput" for configuration "Release"
set_property(TARGET ShishGL-PlatformInput APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ShishGL-PlatformInput PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/shishqa/MIPT/2020_3/02_YAGE/Release/ShishGL/src/Core/RenderSystem/GraphicsPlatform/Input/libShishGL-PlatformInput.a"
  )

# Import target "ShishGL-PlatformEvents" for configuration "Release"
set_property(TARGET ShishGL-PlatformEvents APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ShishGL-PlatformEvents PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/shishqa/MIPT/2020_3/02_YAGE/Release/ShishGL/src/Core/RenderSystem/GraphicsPlatform/Events/libShishGL-PlatformEvents.a"
  )

# Import target "ShishGL-SfmlPlatform" for configuration "Release"
set_property(TARGET ShishGL-SfmlPlatform APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ShishGL-SfmlPlatform PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/shishqa/MIPT/2020_3/02_YAGE/Release/ShishGL/src/Core/RenderSystem/SfmlPlatform/libShishGL-SfmlPlatform.a"
  )

# Import target "ShishGL-Window" for configuration "Release"
set_property(TARGET ShishGL-Window APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ShishGL-Window PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/shishqa/MIPT/2020_3/02_YAGE/Release/ShishGL/src/Core/Window/libShishGL-Window.a"
  )

# Import target "ShishGL-GUI" for configuration "Release"
set_property(TARGET ShishGL-GUI APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ShishGL-GUI PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/shishqa/MIPT/2020_3/02_YAGE/Release/ShishGL/src/GUI/libShishGL-GUI.a"
  )

# Import target "ShishGL-UIWindow" for configuration "Release"
set_property(TARGET ShishGL-UIWindow APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ShishGL-UIWindow PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/shishqa/MIPT/2020_3/02_YAGE/Release/ShishGL/src/GUI/UIWindow/libShishGL-UIWindow.a"
  )

# Import target "ShishGL-Behaviors" for configuration "Release"
set_property(TARGET ShishGL-Behaviors APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ShishGL-Behaviors PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/shishqa/MIPT/2020_3/02_YAGE/Release/ShishGL/src/GUI/UIWindow/Behaviors/libShishGL-Behaviors.a"
  )

# Import target "ShishGL-Shapes" for configuration "Release"
set_property(TARGET ShishGL-Shapes APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ShishGL-Shapes PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/shishqa/MIPT/2020_3/02_YAGE/Release/ShishGL/src/GUI/UIWindow/Shapes/libShishGL-Shapes.a"
  )

# Import target "ShishGL-DebugUtilities" for configuration "Release"
set_property(TARGET ShishGL-DebugUtilities APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ShishGL-DebugUtilities PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/shishqa/MIPT/2020_3/02_YAGE/Release/ShishGL/src/DebugUtilities/libShishGL-DebugUtilities.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
